version: '3'
services:
  web:
    build: .
    image: frida:0.0.1
    restart: always
    command: bash -c "node index.js"
    user: "${UID}:${GID}"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
  redis:
    image: redis
    volumes:
      - ./tmp/db:/var/lib/redis/data
